//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoAndTheBovineClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoAndTheBovineClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _24_settings {
            get {
                object obj = ResourceManager.GetObject("_24_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33CCCC.
        /// </summary>
        public static string ActualColour {
            get {
                return ResourceManager.GetString("ActualColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF7373.
        /// </summary>
        public static string DifferentColour {
            get {
                return ResourceManager.GetString("DifferentColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5CCCCC.
        /// </summary>
        public static string ExpectedColour {
            get {
                return ResourceManager.GetString("ExpectedColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual:.
        /// </summary>
        public static string Label_Actual {
            get {
                return ResourceManager.GetString("Label_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected:.
        /// </summary>
        public static string Label_Expected {
            get {
                return ResourceManager.GetString("Label_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string Label_Result {
            get {
                return ResourceManager.GetString("Label_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 67E667.
        /// </summary>
        public static string SimilarColour {
            get {
                return ResourceManager.GetString("SimilarColour", resourceCulture);
            }
        }
    }
}
